name: Wheel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  #Windows:

   # runs-on: windows-latest

    #steps:
    #- uses: actions/checkout@v3
    #- name: Install dependencies  
    #  run: py -m pip install wheel
    #- name: Build wheel
    #  run: py setup.py bdist_wheel -p win-amd64
      
  macOS:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Mac version
      run: sw_vers
    - name: Install dependencies  
      run: python3 -m pip install twine
    - name: Build wheel
      run: python3 setup.py bdist_wheel -p macosx_10_7_x86_64
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macosx-wheel
        path: dist
